send email sample add
Azure-Samples/communication-services-javascript-quickstarts pull request #64
Opened 2022-05-24 19:19 UTC by moirf

## Purpose

* send email sample add

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: send email sample addition
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-05-24 20:13 UTC, matthohn-msft commented on send-email/README.md
> +  - `Line 13 - <RECIPIENT_EMAIL>`: Replace with recipient email.
Format this line like the others in this list.
 `recipient`: Replace <RECIPIENT_EMAIL> with recipient email.

2022-05-24 20:27 UTC, natekimball-msft requested changes
Just added some minor grammatical considerations. Great work!

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +This sample sends an email to the required recipients of any domain using [Email Communication Services resource](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/email/creat
"...required recipients of any domain using **an** [Email Communication Services resource]..."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +The application is a console based application build using Node.js 14.
"console-based application" should have a hyphen, or just rephrase to "This is a console application build (or _built_) using..."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +1. Open an instance of PowerShell, Windows Terminal, Command Prompt or equivalent and navigate to the directory that you'd like to clone the sample to.
"...Command Prompt, or an equivalent program, and..."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +  - `connectionstring`: Replace `<ACS_CONNECTION_STRING>` with Azure Communication Service resource's connection string.
False possessive. Rephrase to "Replace `<ACS_CONNECTION_STRING>` with the connection string found within the Azure Communication Service resource."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +  - `sender`: Replace `<SENDER_EMAIL>` with sender email obtained from Azure Communication Service.
"Replace `<SENDER_EMAIL>` with **the** sender email..."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +  - `Line 13 - <RECIPIENT_EMAIL>`: Replace with recipient email.
"Replace with **the** recipient email."

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +    - update the connection string, sender email, recipient's email.
- Update the connection string, sender email, and recipient email.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +- [Visual Studio Code (Stable Build)](https://code.visualstudio.com/download)
nit: period at end of sentence.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +- [Node.js (~14)](https://nodejs.org/download/release/v14.19.1/)
nit: period at end of sentence.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +2. Open the send-email.js file to configure the following settings
nit: colon at end of this line.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +    - `npm install` from the root directory
nit: period at end of sentence.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +    - `npm start` from the root directory
nit: period at end of sentence.

2022-05-24 20:27 UTC, natekimball-msft commented on send-email/README.md
> +We appreciate your feedback and energy helping us improve our services. [Please let us know if you are satisfied with ACS through this survey](https://microsoft.qualtrics.com/jfe/form/SV_5dtYL81xwHnU
We appreciate your feedback and energy **in** helping us improve our services.

2022-05-24 23:18 UTC, natekimball-msft approved these changes

2022-05-25 00:37 UTC, kagbakpem approved these changes

2022-05-25 00:37 UTC, merged